---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: ic-claim-app

resources:
# wave 0
- secret-db.yaml
- secret-minio.yaml
# wave 1
- deployment.yaml
- service.yaml
- route.yaml
# wave 2
